#!/usr/bin/env python3
"""Generate the compiled English fallback from the translator-facing catalog."""
import json
from pathlib import Path

project = Path(__file__).resolve().parent.parent
source = project / 'Support/Localization/native-en.json'
strings = json.loads(source.read_text())
# JSON string escaping is also valid Swift here, except JSON's \uXXXX form.
def swift_string(value):
    return json.dumps(value, ensure_ascii=False).replace('\\/', '/')
lines = ['// Generated by scripts/generate-native-localizations.py. Do not edit.',
         'extension InterfaceLocalization {', '    static let englishFallback: [String: String] = [']
for key, value in sorted(strings.items()):
    lines.append(f'        {swift_string(key)}: {swift_string(value)},')
lines += ['    ]', '}', '']
(project / 'Sources/DOTMDLocalization/EnglishFallback.swift').write_text('\n'.join(lines))
